### ISSUE TITLE
How to get this working?

### ISSUE THREAD

**Issue by sasankjonna** [awslabs/aws-lex-net-chatbot#3]
I copied the code to my local . Now none of the documentation talks about how we connect my code to Lex Service I created in my AWS account. The readme says "the code provided can easily connect to any chatbot created with Amazon Lex, and deployed to the web by changing just three configuration options."

What are those three config options?
Am I missing something?

Thanks
SJ

**Comment by sasankjonna** [comment]
Will do more research and come back.

**Comment by tawalke** [comment]
Hi did you get it working.  You needed to change 3 options in the .config file which should have been noted in the documentation. 
For example, once you create your Cognito Identity Pool,  you would update the Cognito pool ID in the config file.  The config file notes which options to change.
